language: java
jdk:
  - oraclejdk8
before_install:
  - gradle wrapper
script:
  - gradle build
  - mkdir JPanel && mkdir JPanel/versions && mkdir JPanel/versions/$TRAVIS_BUILD_NUMBER
  - mv build/libs/PanelPlugin-1.0-SNAPSHOT.jar JPanel-$TRAVIS_BUILD_NUMBER-SNAPSHOT.jar
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
addons:
  artifacts:
    paths:
    - JPanel-$TRAVIS_BUILD_NUMBER-SNAPSHOT.jar
