name: JPanel
version: 1.0-Beta8
description: Adds a web panel to a minecraft server.
author: rymate1234
load: STARTUP

main: net.rymate.jpanel.PanelPlugin
softdepend: [Vault]

commands:
  jpanel:
    description: Information about the current JPanel install
    usage: /<command>
  addlogin:
    description: Adds a user to jPanel
    usage: /<command> [username] [password]
  passwd:
    description: Change the password for a JPanel user
    usage: /<command> [username] [oldpassword] [newpassword]